title: Jens Hömann
logo: "images/ich.jpg"
description: 私の名前はイェンスで、以前は日本北部で国際交流員（CIR）として勤務していましたが、データやプログラミングにも情熱を持っています。私は哲学の修士号を取得しており、ルール大学で教授の研究助手として働いていました。学業と研究の中心は「心の哲学」と「認知科学」で、そこからプログラミングやデータ、統計への関心が芽生えました。Python、SQL、Excel については主にUdemyやYouTubeのコース、そして数多くのオンライン調査を通じて独学で習得しました。

show_downloads: false
theme: jekyll-theme-minimal
